### ISSUE TITLE
Mise en forme Titre 3

### ISSUE THREAD

**Issue by silvaindurand** [yvandouenel/amapl#1]
Peut on mettre une marge en dessous ?

**Comment by yvandouenel** [comment]
Il y en avait déjà une de 10px. Je l'ai doublée (20px). Est-ce que cela te convient ?

**Comment by silvaindurand** [comment]
Elle apparaît en dessus du trait non ?

**Comment by yvandouenel** [comment]
Peux tu me copier les urls pour que je gagne du temps stp ?

**Comment by silvaindurand** [comment]
Non j'ai l'impression qu'il y a une grosse marge entre le texte du titre et la barre, mais pas entre la barre et le texte en dessous...
http://bd.coopernet.fr/cat%C3%A9gories-darticles/cr%C3%A9dit-dimp%C3%B4t-formation-du-chef-dentreprise

**Comment by silvaindurand** [comment]
Tant qu'on y est sur ce titre III, est ce qu'on peut le mettre en gras pour que ça rende comme sur http://bd.coopernet.fr/cat%C3%A9gories-darticles/b%C3%A9n%C3%A9ficiaires ?

**Comment by yvandouenel** [comment]
C'est fait.
