### ISSUE TITLE
Peut on voir si la façon de rédiger est correcte ?

### ISSUE THREAD

**Issue by silvaindurand** [yvandouenel/amapl#2]
http://bd.coopernet.fr/cat%C3%A9gories-darticles/d%C3%A9ductions-%C2%AB-m%C3%A9decins-conventionn%C3%A9s-de-secteur-1-%C2%BB

DÉDUCTION DE 2 % REPRÉSENTATIVE DE CERTAINS FRAIS

**Comment by yvandouenel** [comment]
Oui, nous avons vu que c'était correct. Tu peux utiliser <br> pour passer à la ligne : c'est fait pour ça. En revanche si tu utilises plusieurs <br>, c'est qu'il y a un pb...
