### ISSUE TITLE
Div pour les actualités

### ISSUE THREAD

**Issue by silvaindurand** [yvandouenel/amapl#24]
http://bd.coopernet.fr/Node/620#

Dans cet exemple, j'ai inséré manuellement un plan avec des liens vers des ancres et un revenir au sommaire sous chaque tableau.

Pour le revenir au sommaire, est ce qu'on pourrait créer une DIV spécifique qui ferait apparaître le texte (revenir au sommaire) et le lien (c'est toujours le même #sommaire) avec la mise en forme souhaitée ? 

Pour le titre, j'ai repris la DIV en-valeur avec une couleur orange du texte. Est qu'on peut créer une DIV appelée ActuT qui serait la même que le DIV en-valeur avec la couleur orange du texte Rgb(241,91,65)
?

**Comment by yvandouenel** [comment]
J'ai ajouté un bouton dans l'éditeur de texte (le dernier) qui permet d'ajouter du code html sous forme d'un template. Il n'y a qu'un seul template qui écrit "Retour au sommaire". Dis moi quelle mise en forme tu souhaites ?
Par ailleurs j'ai créé une class ActuT qui fait, je crois, ce que tu demandes. Dis moi si cela fonctionne.

**Comment by silvaindurand** [comment]
1/
margin-top:50px
margin-bottom:70px
style="font-size:9px"
Même couleur que la classe orange des liens

2/Non, cela n'a pas l'air de fonctionner
http://www.vigipl.com/actualites/test

**Comment by yvandouenel** [comment]
Entendu, c'est corrigé mais si ça ne te pose pas de problème, je préfère nettement que la classe utilisée soit "actu-t" et non pas "ActuT". Cette dernière syntaxe (CamelCase) est réservée au languages de programmation. Pour les feuilles de style sous drupal, on utilise le trait d'union sans majuscule.
