### ISSUE TITLE
Lien de type /taxonomy/term/130#node-article-153

### ISSUE THREAD

**Issue by silvaindurand** [yvandouenel/amapl#26]
les liens de type /taxonomy/term/130#node-article-153, vont sur le terme mais pas sur l'article comme auparavant.

Exemple : http://bd.coopernet.fr/taxonomy/term/134
V. le premier lien orange

**Comment by yvandouenel** [comment]
Remettre des liens et des ancres du type #node-article-153

**Comment by silvaindurand** [comment]
ok fait
