### ISSUE TITLE
DIV ESPACE

### ISSUE THREAD

**Issue by silvaindurand** [yvandouenel/amapl#28]
Créer une dive correspondant à un saut de ligne

**Comment by yvandouenel** [comment]
J'ai fait des tests mais je ne suis pas sûr de comprendre exactement ce que tu veux. Peut-on en parler pour préciser ?

**Comment by silvaindurand** [comment]
L'idée c'est que parfois je veux juste sauter une ligne pour aérer, et comme il ne faut pas sauter des lignes, c'était de créer une DIV pour aérer un peu !!!

**Comment by yvandouenel** [comment]
Entendu, j'ai créé un modèle de div "saut ligne" qui utilisera la class "break-line". Peux tu tester stp ?
