### ISSUE TITLE
Prévoir La connexion en tant que Masquerade

### ISSUE THREAD

**Issue by silvaindurand** [yvandouenel/amapl#29]
Prévoir La connexion en tant que Masquerade

**Comment by yvandouenel** [comment]
Le site est trop complexe pour que Masquerade fonctionne. Il y a une mauvaise interaction entre masquerade et le mécanisme qui fait en sorte que l'on est renvoyé vers un site quand on se déconnecte. Si c'est important, je creuse plus mais ça risque de prendre du temps.

**Comment by silvaindurand** [comment]
Franchement je ne sais plus pourquoi nous avions évoqué cela car je ne sais même pas ce que cela veut dire et il me semble que c'était d'avoir accès à tous les comptes vite pour pouvoir passer de l'un à l'autre...
En tous cas au fil d'une conversation tu m'avais dit de l'intégrer à une prochaine évolution et que c'était assez simple. 
Si c'est plus compliqué, on clos donc.
