### ISSUE TITLE
Non mise à jour sur bd.coopernet d'une modification faite le 10/03/2016

### ISSUE THREAD

**Issue by silvaindurand** [yvandouenel/amapl#30]
L'insertion d'une actualité dans un article ne semble pas avoir été effectivement reprise sur bd.coopernet.fr

http://bd.coopernet.fr/cat%C3%A9gories-darticles/seuils-pour-les-exercices-clos-%C3%A0-compter-du-31-d%C3%A9cembre-2015

Sur l'article Réforme des seuils.

**Comment by yvandouenel** [comment]
Je n'arrive pas à voir de différence avec http://www.vigipl.com/cat%C3%A9gories-darticles/seuils-pour-les-exercices-clos-%C3%A0-compter-du-31-d%C3%A9cembre-2015#node-article-651... peux tu m'éclairer ?

**Comment by silvaindurand** [comment]
Ca y est j'ai trouvé...En fait, j'avais associé une actualité liée à l(article, et cela n'apparaît plus dans l'article comme cela apparaissait auparavant avant la mise à jour...Evidemment, la différence n'apparaît plus maintenant que vigipl a été repris de bd.coopernet !

![capture](https://cloud.githubusercontent.com/assets/17548642/16270570/118e349c-3897-11e6-985f-c26bbfd77e97.PNG)
