### ISSUE TITLE
Pour modifier la page d'accueil du site

### ISSUE THREAD

**Issue by silvaindurand** [yvandouenel/amapl#31]
Je ne trouve pas comment modifier la page d'accueil du site : 
www.bd.coopernet.fr

**Comment by yvandouenel** [comment]
Dis moi ce que tu veux modifier exactement ?

**Comment by silvaindurand** [comment]
Yvan

Je suppose que je cherchais à modifier la page d’accueil du site des gens non identifiés (vigipl.com) quand c’était sur bd.coopernet.fr car tout était en titre 2, et c’est une page à laquelle on n’accède pas facilement quand on est identifié.

La page est correcte désormais, c’est que j’ai dû y accéder ou te demander de le faire…

Si tu peux me dire comment y accéder, je le noterai une fois pour toutes :) 

Silvain

De : Yvan Douënel [mailto:notifications@github.com] 
Envoyé : lundi 20 juin 2016 17:19
À : yvandouenel/amapl amapl@noreply.github.com
Cc : silvaindurand silvain.durand@amapl.com; Author author@noreply.github.com
Objet : Re: [yvandouenel/amapl] Pour modifier la page d'accueil du site (#31)

Dis moi ce que tu veux modifier exactement ?

**Comment by yvandouenel** [comment]
Tout ce qui disparait en fonction de l'identification de l'internaute se trouve dans des "blocks". Pour visualiser les blocs, l'adresse est : http://www.vigipl.com/admin/content/blocks. Tu peux également passer par le menu d'administration : Contenu > blocs. Ensuite, tu peux modifier un bloc de la liste en cliquant sur le lien "Modifier" correspondant. Pour les logos de page d'accueil, il s'agit du bloc "block_front" .
