### ISSUE TITLE
Lien exerne vers un atom 

### ISSUE THREAD

**Issue by silvaindurand** [yvandouenel/amapl#35]
Lien exerne vers un atom permettant de voir la PJ.
Ne faut il pas bloquer ?
http://www.vigipl.com/atom/38

**Comment by yvandouenel** [comment]
Je viens de bloquer l'accès à l'atom mais si l'internaute a le lien définitif du fichier (ici http://www.vigipl.com/sites/bdpl.fr/files/atoms/files/madelinlimitesrevenusde2015misenligne_0.xls) alors, il pourra y accéder. Je peux faire en sorte que ce ne soit plus possible mais j'en ai pour 2 heures de travail...
