### ISSUE TITLE
Mise en forme du Titre 4

### ISSUE THREAD

**Issue by silvaindurand** [yvandouenel/amapl#4]
Peut-on mettre une barre sous le Titre 4, et augmenter les marges hautes et basses ?

**Comment by yvandouenel** [comment]
C'est fait.

**Comment by silvaindurand** [comment]
Tu peux augmenter la marge du haut ? Comme celle du Titre 3 ?

**Comment by yvandouenel** [comment]
Je crois que c'est fait mais si ça ne va tjs pas, il faut que tu sois plus précis... en fait, il faudrait que tu puisses tester de ton coté et me dire la taille exacte que tu veux. On verras cela mercredi après-midi ou la semaine prochaine.

**Comment by silvaindurand** [comment]
Juste mettre en gras le titre 4, et là on est bons pour la mise en forme des titres....
