### ISSUE TITLE
Visualisation des tableaux par défaut

### ISSUE THREAD

**Issue by silvaindurand** [yvandouenel/amapl#5]
Peut-on mettre les tableaux qui n'ont pas de bordure par défaut avec une bordure grisée (comme c'était le cas sur vigipl ?)

http://bd.coopernet.fr/cat%C3%A9gories-darticles/exon%C3%A9ration-des-plus-values-de-cession-de-branche-compl%C3%A8te-dactivit%C3%A9

**Comment by yvandouenel** [comment]
C'est fait

**Comment by silvaindurand** [comment]
Peut on mettre en forme comme sur VIGIPL 
- Sur vigipl, http://www.vigipl.com/cat%C3%A9gories-darticles/seuils-pour-les-exercices-clos-avant-le-31-d%C3%A9cembre-2015
- Sur version en cours, http://bd.coopernet.fr/cat%C3%A9gories-darticles/seuils-pour-les-exercices-clos-avant-le-31-d%C3%A9cembre-2015
- Mettre une marge Bottom par défaut de 2em ?

**Comment by yvandouenel** [comment]
Entendu, c'est fait.
