### ISSUE TITLE
Mentions légales et plan du site

### ISSUE THREAD

**Issue by silvaindurand** [yvandouenel/amapl#7]
Sur la barre du bas, peut-on mettre les Mentions légales et plan du site en blanc, en haut de la barre ?

**Comment by yvandouenel** [comment]
C'est fait.

**Comment by silvaindurand** [comment]
Sur la lecture portable, on ne voit apparaitre que les mentions légales, et elles sont coupées...

**Comment by silvaindurand** [comment]
OK fait
