### ISSUE TITLE
Mise en forme des actualités

### ISSUE THREAD

**Issue by silvaindurand** [yvandouenel/amapl#8]
- Le titre : Pas en majuscule et plus petit
- Laisser l'icone imprimante mais enlever le mot Imprimer. - Mettre à côté la date de mise en ligne : "mis en ligne le ......". Faire une marge de 30 en bas (après la date et avant le début de l'actualité).
- Par défaut, est ce que le texte peut prendre les deux tiers du care, l'autre tiers étant réservé aux liens et références. Laisser cette mise en forme (2/3) même s'il n'y a pas de lien ou référence. Pour les liens ou références, les mettre sous fond gris, en indiquant "A lire aussi". Mettre un lien orange sous fond gris (un peu comme actuellement sur VIGIPL). Aller à la ligne entre chaque lien ou référence.

**Comment by yvandouenel** [comment]
Quand tu parles des "liens et références", je comprends bien les "références" puisqu'il y a un champ "références", en revanche, les liens correspondent-ils aux "actualités liées ?"

**Comment by silvaindurand** [comment]
Salut Yvan. Oui les 2

**Comment by silvaindurand** [comment]
OK fait
