### ISSUE TITLE
Mise en forme de la vue de la liste des actualités et des références

### ISSUE THREAD

**Issue by silvaindurand** [yvandouenel/amapl#9]
http://bd.coopernet.fr/actualites
http://bd.coopernet.fr/references

Il y a écrit à chaque fois Références puis en dessous Références (idem actualités), Peut-on indiquer seulement une seule fois, selon le même modèle que "bienvenue sur votre espace documentaire en ligne sur la page d'accueil ?

**Comment by yvandouenel** [comment]
Le module de fil d'Ariane ne prévoit pas ce cas de figure. Dis moi si cela vaut la peine que je teste, installe et configure un autre module pour cela

**Comment by silvaindurand** [comment]
Non ce n'est pas la peine...
